pvesm_local_storage_path: /mnt/pve/ds1618
pvesm_local_storage_iso_subpath: template/iso

iso_images_to_download:
- filename: ubuntu-22.04-server-cloudimg-amd64.img
  url: https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img
  is_cloud_init_image: true
  cloud_init_vm_id: 9001
  cloud_init_vm_instance_template_name: ubuntu-22.04-server-cloudimg-amd64
  enable_qemu_guest_agent: true
